name: integrate
dependencies:
- cycler=0.10.0=py35_0
- decorator=4.0.9=py35_0
- et_xmlfile=1.0.1=py35_0
- fontconfig=2.11.1=5
- freetype=2.5.5=0
- ipykernel=4.3.1=py35_0
- ipython=4.1.2=py35_0
- ipython_genutils=0.1.0=py35_0
- ipywidgets=4.1.1=py35_0
- jdcal=1.2=py35_0
- jinja2=2.8=py35_0
- jsonschema=2.4.0=py35_0
- jupyter=1.0.0=py35_1
- jupyter_client=4.2.2=py35_0
- jupyter_console=4.1.1=py35_0
- jupyter_core=4.1.0=py35_0
- libgfortran=3.0=0
- libpng=1.6.17=0
- libsodium=1.0.3=0
- libxml2=2.9.2=0
- markupsafe=0.23=py35_0
- matplotlib=1.5.1=np110py35_0
- mistune=0.7.1=py35_0
- mkl=11.3.1=0
- nbconvert=4.1.0=py35_0
- nbformat=4.0.1=py35_0
- notebook=4.1.0=py35_0
- numexpr=2.5=np110py35_0
- numpy=1.10.4=py35_1
- openssl=1.0.2g=0
- pandas=0.17.1=np110py35_0
- path.py=8.1.2=py35_1
- pexpect=3.3=py35_0
- pickleshare=0.5=py35_0
- pip=8.1.0=py35_0
- ptyprocess=0.5=py35_0
- pygments=2.1.1=py35_0
- pyparsing=2.0.3=py35_0
- pyqt=4.11.4=py35_1
- python=3.5.1=0
- python-dateutil=2.4.2=py35_0
- pytz=2015.7=py35_0
- pyzmq=15.2.0=py35_0
- qt=4.8.7=1
- qtconsole=4.1.1=py35_0
- readline=6.2=2
- requests=2.9.1=py35_0
- scipy=0.17.0=np110py35_2
- seaborn=0.7.0=py35_0
- setuptools=20.2.2=py35_0
- simplegeneric=0.8.1=py35_0
- sip=4.16.9=py35_0
- six=1.10.0=py35_0
- sqlite=3.9.2=0
- terminado=0.5=py35_1
- tk=8.5.18=0
- tornado=4.3=py35_0
- traitlets=4.1.0=py35_0
- wheel=0.29.0=py35_0
- xlsxwriter=0.8.4=py35_0
- xz=5.0.5=1
- zeromq=4.1.3=0
- zlib=1.2.8=0
- pip:
  - et-xmlfile==1.0.1
  - hetio (/home/dhimmels/Documents/github/hetio)==0.1.0
  - ipython-genutils==0.1.0
  - jupyter-client==4.2.2
  - jupyter-console==4.1.1
  - jupyter-core==4.1.0
  - py2neo==2.0.8

